name: Apply

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
  TF_IN_AUTOMATION: true
  TF_INPUT: false

permissions:
  id-token: write

jobs:
  security-scan:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Scan
        run: docker run -v ${PWD}:/src aquasec/tfsec:v1.8 /src

  apply:
    runs-on: ubuntu-20.04

    needs:
      - security-scan

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Init
        run: terraform init -backend-config="bucket=${{ secrets.TERRAFORM_STATE_BUCKET }}"
      - name: Apply
        run: terraform apply --auto-approve
